### ISSUE TITLE
Create TableView component

### ISSUE THREAD

**Issue by Panupong026** [chonnikan-aue/money-spendee-client#3]
- Merged created component w/ main

**Comment by ougrid** [comment]
- [x] Show data from DB
- [x] Make Edit button work
  - [x] Update table without reloading the whole page
  - [ ] Make it pre-filled with selected transaction 
  - [ ] UPDATE to DB
- [x] Make Delete button work
  - [ ] Update table without reloading the whole page
  - [ ] Apply Delete function to withdrawsList
  - [x] Apply Delete function to depositsList  
  - [x] DELETE from DB
- [ ] Create 'sort by column' feature
- [ ] Make Pagination work 
- [ ] Change date format
